use northwind;

-- ============= null========================================================

select minimum_reorder_quantity
from products
where minimum_reorder_quantity=null;-- anything compared with null will give empty table/output

select '' and null;
select concat('hi',null);

-- ========================= aggregate count ===============================

select count(*) from employees;
select count(employee) from employees;
select count(ID) from employees;
select * from employees;
-- 
select count(distinct(employee_id)) from orders where customer_id is not null;
--  count the no of customer from ship_city='new york'
select count(distinct(customer_id)) from orders where ship_city='New York';

-- ==========================aggregate sum ======================

use hr;
select sum(salary) from employees;
use northwind;
select sum(minimum_reorder_quantity) from products;

--  find the total revenue generated by the company

select * from order_details;
select sum(quantity* unit_price) from order_details;

-- ====================average aggregate ====================

select avg(salary) from hr.employees;
select avg(unit_price)  avg_unit from northwind.order_details;
select avg(quantity) as avg_quantity from northwind.order_details;

-- ========================= min /max  aggregate ===============================

select min(unit_price) as minum_unit, max(unit_price) as max_unit from northwind.order_details;

-- ======================== group by ===========================================

select count(department_id) no_of_emp_dept,FIRST_NAME
from hr.employees
group by FIRST_NAME;
use northwind;
select category, count(*) no_of_product_cat
from products
group by category
order by no_of_product_cat desc;

select department_id, count(department_id) no_of_emp_dept
from hr.employees; 

select salary,count(*) as count1
from hr.employees
group by salary;
select count(*) customer_id, count(id)  from orders group by customer_id;
-- find the taotal revenue for each product 
-- select sum(unit*) from orders
-- find the number of employees who has been hired in befor 1998 for each dept
select count(*) ,department_id;

-- maximum salary in each dept
select department_id, max(salary) as max_salary
from hr.employees
group by department_id
order by max_salary desc;

-- min salary in each dept
select department_id, min(salary) as min_salary
from hr.employees
group by department_id
order by min_salary ;

-- find mean and max salary for each job id where dept id is 80

select department_id, max(salary) as min_salary,avg(salary) as mean
from hr.employees
group by department_id=80;

-- find distinct job role in each dept
select distinct(job_desc),department_id, FIRST_NAME
from hr.employees
group by department_id;


-- select @@sql_mode; 
-- set session sql_mode=concat(@@sql_mode,'only_full_group_by');

select manager_id,count(*) as no_of
from hr.employees
group by MANAGER_ID
having no_of>=5
order by no_of desc;

-- no of custoers who have  placed more than 5 order
select * from northwind.orders;

select customer_id,count(*) as no_of
from northwind.orders
group by customer_id
having no_of>=5
order by no_of desc;

-- find the shipper who has shipped more than 100 orderdere in 1997
select * from northwind.orders;

select shipper_id,count(*) as  no_of  from  orders where year(shipped_date)=2006 group by shipper_id having count(*)>=10;

-- select * from 
-- find the department whose total salary exceeds 50000
select department_id , sum(salary) as total_sal
from hr.employees
group by department_id
having total_sal>50000;
-- find the dept whoes avg slary is b/w 5000 to 10000

select department_id, avg(salary) as avg_sal
from hr.employees
group by department_id
 having avg_sal between 5000 and 10000;
 -- find  the dept min salary and max_slary is greater than 5000
 
 select department_id ,min(salary) as min_sal,max(salary)as max_sal
 from hr.employees
 group by department_Id
 having max_sal-min_sal>5000;
 
 select
 case 
	when salary<5000 then 'low sal'
    when salary<10000 then 'mid range sal'
    when salary<50000 then 'high range sal'
    else 'high'
    end as salary_band, count(*) no_of , min(salary) as min_sal,
    max(salary) max_sal from hr.employees
    group by
    case
		when salary<5000 then 'low sal'
        when salary<10000 then 'mid range sal'
        when salary<50000 then 'high range sal'
        else 'high'
	end
    order by salary_band desc;
    
    
    select * from hr.employees